export const countryToCurrency: Record<string, string> = {
  "Afghanistan": "؋",
  "Albania": "Lek",
  "Algeria": "د.ج",
  "Andorra": "€",
  "Angola": "Kz",
  "Antigua and Barbuda": "$",
  "Argentina": "$",
  "Armenia": "֏",
  "Australia": "A$",
  "Austria": "€",
  "Azerbaijan": "₼",
  "Bahamas": "$",
  "Bahrain": ".د.ب",
  "Bangladesh": "৳",
  "Barbados": "$",
  "Belarus": "Br",
  "Belgium": "€",
  "Belize": "BZ$",
  "Benin": "CFA",
  "Bhutan": "Nu.",
  "Bolivia": "Bs.",
  "Bosnia and Herzegovina": "KM",
  "Botswana": "P",
  "Brazil": "R$",
  "Brunei": "B$",
  "Bulgaria": "лв",
  "Burkina Faso": "CFA",
  "Burundi": "FBu",
  "Cabo Verde": "Esc",
  "Cambodia": "៛",
  "Cameroon": "CFA",
  "Canada": "C$",
  "Central African Republic": "CFA",
  "Chad": "CFA",
  "Chile": "$",
  "China": "¥",
  "Colombia": "$",
  "Comoros": "CF",
  "Congo": "FC",
  "Costa Rica": "₡",
  "Croatia": "€",
  "Cuba": "$",
  "Cyprus": "€",
  "Czech Republic": "Kč",
  "Denmark": "kr",
  "Djibouti": "Fdj",
  "Dominica": "$",
  "Dominican Republic": "RD$",
  "Ecuador": "$",
  "Egypt": "£",
  "El Salvador": "$",
  "Equatorial Guinea": "CFA",
  "Eritrea": "Nfk",
  "Estonia": "€",
  "Eswatini": "L",
  "Ethiopia": "Br",
  "Fiji": "$",
  "Finland": "€",
  "France": "€",
  "Gabon": "CFA",
  "Gambia": "D",
  "Georgia": "₾",
  "Germany": "€",
  "Ghana": "GH₵",
  "Greece": "€",
  "Grenada": "$",
  "Guatemala": "Q",
  "Guinea": "FG",
  "Guinea-Bissau": "CFA",
  "Guyana": "$",
  "Haiti": "G",
  "Honduras": "L",
  "Hungary": "Ft",
  "Iceland": "kr",
  "India": "₹",
  "Indonesia": "Rp",
  "Iran": "﷼",
  "Iraq": "ع.د",
  "Ireland": "€",
  "Israel": "₪",
  "Italy": "€",
  "Jamaica": "$",
  "Japan": "¥",
  "Jordan": "د.ا",
  "Kazakhstan": "₸",
  "Kenya": "KSh",
  "Kiribati": "$",
  "Korea, North": "₩",
  "Korea, South": "₩",
  "Kosovo": "€",
  "Kuwait": "د.ك",
  "Kyrgyzstan": "лв",
  "Laos": "₭",
  "Latvia": "€",
  "Lebanon": "£",
  "Lesotho": "L",
  "Liberia": "$",
  "Libya": "ل.د",
  "Liechtenstein": "CHF",
  "Lithuania": "€",
  "Luxembourg": "€",
  "Madagascar": "Ar",
  "Malawi": "MK",
  "Malaysia": "RM",
  "Maldives": "Rf",
  "Mali": "CFA",
  "Malta": "€",
  "Marshall Islands": "$",
  "Mauritania": "UM",
  "Mauritius": "₨",
  "Mexico": "$",
  "Micronesia": "$",
  "Moldova": "L",
  "Monaco": "€",
  "Mongolia": "₮",
  "Montenegro": "€",
  "Morocco": "د.م.",
  "Mozambique": "MT",
  "Myanmar": "K",
  "Namibia": "$",
  "Nauru": "$",
  "Nepal": "₨",
  "Netherlands": "€",
  "New Zealand": "$",
  "Nicaragua": "C$",
  "Niger": "CFA",
  "Nigeria": "₦",
  "North Macedonia": "ден",
  "Norway": "kr",
  "Oman": "ر.ع.",
  "Pakistan": "₨",
  "Palau": "$",
  "Panama": "B/.",
  "Papua New Guinea": "K",
  "Paraguay": "₲",
  "Peru": "S/.",
  "Philippines": "₱",
  "Poland": "zł",
  "Portugal": "€",
  "Qatar": "ر.ق",
  "Romania": "lei",
  "Russia": "₽",
  "Rwanda": "FRw",
  "Saint Kitts and Nevis": "$",
  "Saint Lucia": "$",
  "Saint Vincent and the Grenadines": "$",
  "Samoa": "T",
  "San Marino": "€",
  "Sao Tome and Principe": "Db",
  "Saudi Arabia": "ر.س",
  "Senegal": "CFA",
  "Serbia": "дин.",
  "Seychelles": "₨",
  "Sierra Leone": "Le",
  "Singapore": "S$",
  "Slovakia": "€",
  "Slovenia": "€",
  "Solomon Islands": "$",
  "Somalia": "S",
  "South Africa": "R",
  "South Sudan": "£",
  "Spain": "€",
  "Sri Lanka": "₨",
  "Sudan": "ج.س.",
  "Suriname": "$",
  "Sweden": "kr",
  "Switzerland": "CHF",
  "Syria": "£",
  "Taiwan": "NT$",
  "Tajikistan": "ЅМ",
  "Tanzania": "TSh",
  "Thailand": "฿",
  "Timor-Leste": "$",
  "Togo": "CFA",
  "Tonga": "T$",
  "Trinidad and Tobago": "TT$",
  "Tunisia": "د.ت",
  "Turkey": "₺",
  "Turkmenistan": "T",
  "Tuvalu": "$",
  "Uganda": "USh",
  "Ukraine": "₴",
  "United Arab Emirates": "AED",
  "United Kingdom": "£",
  "United States": "$",
  "Uruguay": "$U",
  "Uzbekistan": "лв",
  "Vanuatu": "VT",
  "Vatican City": "€",
  "Venezuela": "Bs.",
  "Vietnam": "₫",
  "Yemen": "﷼",
  "Zambia": "ZK",
  "Zimbabwe": "$",
  "United States of America": "$"
};
