'use client';

import { motion } from 'framer-motion';
import { Shield, Lock, Scale, FileText, ChevronLeft, ArrowRight } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';

const DOCUMENTS = [
  {
    id: 'privacy',
    title: 'Privacy Policy',
    icon: <Lock className="w-4 h-4" />,
    version: 'v2.0 // Absolute Zero',
    content: (
      <div className="space-y-8 text-sm leading-relaxed font-light text-white/70">
        <section className="space-y-4">
          <h3 className="text-white font-bold tracking-tight uppercase text-xs">1. Data Minimization Protocol</h3>
          <p>We do not store your personal identifiable information (PII) on our permanent intelligence servers. Your role data, skill matrix, and financial targets are processed in-memory during your active session.</p>
          <p>All intelligence is processed via the <span className="text-blue-400 font-mono text-[10px]">Google Gemma 3</span> neural engine using enterprise-grade, non-training protocols. Your data is never used to train future iterations of the model.</p>
        </section>

        <section className="space-y-4">
          <h3 className="text-white font-bold tracking-tight uppercase text-xs">2. Temporal Grounding & Search</h3>
          <p>The Market Pulse engine utilizes real-time Google Search Grounding. Your search queries are anonymized before being transmitted to external search providers to ensure your tactical intent remains private.</p>
        </section>

        <section className="space-y-4">
          <h3 className="text-white font-bold tracking-tight uppercase text-xs">3. Zero-Retention Dossiers</h3>
          <p>Once your Tactical Dossier (PDF) is generated, all temporary session data is purged from our active memory buffers. The Platform does not maintain a repository of generated roadmaps; once downloaded, the intelligence is solely in your possession.</p>
        </section>

        <section className="space-y-4">
          <h3 className="text-white font-bold tracking-tight uppercase text-xs">4. Encryption & Security</h3>
          <p>All data in transit is protected by AES-256 grade encryption. Your uplink to the Guardian Command Center is secured via high-authority SSL/TLS 1.3 protocols.</p>
        </section>
      </div>
    )
  },
  {
    id: 'terms',
    title: 'Terms of Service',
    icon: <Scale className="w-4 h-4" />,
    version: 'v2.0 // Tactical Authorization',
    content: (
      <div className="space-y-8 text-sm leading-relaxed font-light text-white/70">
        <section className="space-y-4">
          <h3 className="text-white font-bold tracking-tight uppercase text-xs">1. Scope of Service</h3>
          <p>The Guardian OS provides predictive AI career diagnostics and tactical roadmaps. These outputs are derived from 2026 market benchmarks and regional geospatial intelligence. The Platform is a tool for strategic simulation and resilience planning.</p>
        </section>

        <section className="space-y-4">
          <h3 className="text-white font-bold tracking-tight uppercase text-xs text-red-400">2. No Financial or Legal Advice</h3>
          <p className="border-l-2 border-red-500/30 pl-4 py-1 italic">The "Tactical Dossiers" and "Pivot Roadmaps" generated by the Platform are for informational purposes only. The Guardian OS does not provide legally binding financial, legal, or career advice. All decisions made based on the Platform's intelligence are the sole responsibility of the operative.</p>
        </section>

        <section className="space-y-4">
          <h3 className="text-white font-bold tracking-tight uppercase text-xs">3. Intellectual Property</h3>
          <p>The underlying "Guardian Neural Engine," its visual aesthetic, and its proprietary diagnostic algorithms are the intellectual property of <span className="text-blue-400">Priiyo</span>. You are granted a limited, non-transferable license to use the Platform for personal career resilience planning.</p>
        </section>

        <section className="space-y-4">
          <h3 className="text-white font-bold tracking-tight uppercase text-xs">4. Prohibited Actions</h3>
          <p>Operatives are strictly prohibited from attempting to reverse-engineer the "Neural Sync" or "Grounding" protocols, using the Platform for malicious intent, or deploying automated scrapers against the Market Pulse engine.</p>
        </section>
      </div>
    )
  },
  {
    id: 'security',
    title: 'Security Protocol',
    icon: <Shield className="w-4 h-4" />,
    version: 'v2.0 // Neural Shield',
    content: (
      <div className="space-y-8 text-sm leading-relaxed font-light text-white/70">
        <section className="space-y-4">
          <h3 className="text-white font-bold tracking-tight uppercase text-xs">1. Active Defense Protocols</h3>
          <p>We maintain a strict 48-hour Tactical Response Window. Any identified breaches in the Monetization Uplink or Intelligence Sector are patched and verified with mission-critical urgency.</p>
        </section>

        <section className="space-y-4">
          <h3 className="text-white font-bold tracking-tight uppercase text-xs">2. Hardened Encryption</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-4">
            <div className="p-4 rounded-xl bg-white/5 border border-white/10">
              <div className="text-[10px] font-mono text-blue-400 mb-1 uppercase tracking-widest text-center">HMAC-SHA256</div>
              <div className="text-[9px] opacity-40 text-center uppercase">Payment Integrity</div>
            </div>
            <div className="p-4 rounded-xl bg-white/5 border border-white/10">
              <div className="text-[10px] font-mono text-blue-400 mb-1 uppercase tracking-widest text-center">AES-256 / TLS 1.3</div>
              <div className="text-[9px] opacity-40 text-center uppercase">Neural Uplink</div>
            </div>
          </div>
        </section>

        <section className="space-y-4">
          <h3 className="text-white font-bold tracking-tight uppercase text-xs">3. Sector Isolation</h3>
          <p>The platform utilizes Supabase Row-Level Security (RLS) for absolute isolation of intelligence session data. Temporary session memory is automatically purged post-dossier generation.</p>
        </section>
      </div>
    )
  },
  {
    id: 'license',
    title: 'Tactical License',
    icon: <FileText className="w-4 h-4" />,
    version: 'v2.0 // Proprietary Command',
    content: (
      <div className="space-y-8 text-sm leading-relaxed font-light text-white/70">
        <section className="space-y-4">
          <h3 className="text-white font-bold tracking-tight uppercase text-xs">1. Proprietary Authorization</h3>
          <p>The software, intelligence core, and visual HUD assets are the proprietary property of <span className="text-blue-400">Priiyo</span> and the Guardian Intelligence Command. Unauthorized duplication or redistribution is strictly prohibited.</p>
        </section>

        <section className="space-y-4">
          <h3 className="text-white font-bold tracking-tight uppercase text-xs">2. Operational License</h3>
          <p>Operatives are granted a limited license for personal career resilience. Commercial redistribution of the underlying "Guardian Neural Engine" requires an explicit Command-Tier Authorization.</p>
        </section>

        <section className="space-y-4 text-[10px] font-mono uppercase tracking-[0.2em] pt-8 text-center text-blue-500/50">
          STAY SECURE. SURVIVE BY DESIGN.
        </section>
      </div>
    )
  }
];

export default function LegalPage() {
  const [activeTab, setActiveTab] = useState(DOCUMENTS[0].id);

  return (
    <main className="min-h-screen bg-[#020617] text-white selection:bg-blue-500/30">
      {/* Background Ambience */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[600px] bg-blue-500/5 blur-[120px] rounded-full" />
        <div className="absolute bottom-0 left-0 w-full h-[30vh] bg-gradient-to-t from-blue-500/5 to-transparent" />
      </div>

      <div className="container mx-auto px-4 py-20 relative z-10">
        <div className="max-w-5xl mx-auto space-y-16">
          
          {/* Header */}
          <div className="space-y-6">
            <Link href="/" className="inline-flex items-center gap-2 text-xs font-mono text-blue-400/60 hover:text-blue-400 transition-colors group">
              <ChevronLeft className="w-3 h-3 group-hover:-translate-x-1 transition-transform" /> Back to Command Center
            </Link>
            <div className="space-y-2">
              <h1 className="text-4xl md:text-6xl font-black tracking-tighter uppercase italic">
                Legal & <span className="text-blue-500">Protocol.</span>
              </h1>
              <p className="text-sm text-muted-foreground font-mono uppercase tracking-[0.3em]">
                System Hardening // v1.1.0 // Auth: Priiyo
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
            
            {/* Sidebar Navigation */}
            <aside className="lg:col-span-4 space-y-4">
              <div className="text-[10px] font-mono uppercase tracking-[0.4em] text-white/20 mb-6">Sector Navigation</div>
              <div className="flex flex-col gap-2">
                {DOCUMENTS.map((doc) => (
                  <button
                    key={doc.id}
                    onClick={() => setActiveTab(doc.id)}
                    className={`flex items-center gap-4 p-4 rounded-2xl border transition-all text-left group ${
                      activeTab === doc.id 
                        ? 'bg-blue-500/10 border-blue-500/30 text-white shadow-[0_0_20px_rgba(59,130,246,0.1)]' 
                        : 'bg-white/5 border-white/5 text-white/40 hover:bg-white/10 hover:border-white/10 hover:text-white/60'
                    }`}
                  >
                    <div className={`p-2 rounded-xl transition-colors ${
                      activeTab === doc.id ? 'bg-blue-500 text-white' : 'bg-white/5 text-white/40'
                    }`}>
                      {doc.icon}
                    </div>
                    <div>
                      <div className="text-xs font-bold tracking-tight uppercase">{doc.title}</div>
                      <div className="text-[9px] font-mono opacity-40 uppercase tracking-widest mt-0.5">{doc.version}</div>
                    </div>
                    {activeTab === doc.id && (
                      <div className="ml-auto">
                        <ArrowRight className="w-3 h-3 text-blue-400" />
                      </div>
                    )}
                  </button>
                ))}
              </div>

              {/* Status HUD */}
              <div className="mt-12 p-6 rounded-3xl bg-blue-500/5 border border-blue-500/10 space-y-4">
                <div className="text-[10px] font-mono uppercase tracking-widest text-blue-400/60">System Security Status</div>
                <div className="space-y-2">
                  <StatusRow label="Encryption" value="AES-256" />
                  <StatusRow label="Protocols" value="TLS 1.3" />
                  <StatusRow label="Data Store" value="Zero-Retention" />
                  <StatusRow label="Gemma Auth" value="Enterprise" />
                </div>
              </div>
            </aside>

            {/* Content Area */}
            <div className="lg:col-span-8">
              <motion.div
                key={activeTab}
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.5 }}
                className="bg-white/5 border border-white/10 rounded-[2rem] p-8 md:p-12 shadow-2xl relative overflow-hidden"
              >
                {/* Decorative Elements */}
                <div className="absolute top-0 right-0 w-32 h-32 bg-blue-500/5 blur-[40px] rounded-full -translate-y-1/2 translate-x-1/2" />
                
                <div className="relative z-10 space-y-12">
                  <div className="flex items-center justify-between border-b border-white/5 pb-8">
                    <div className="space-y-1">
                      <h2 className="text-2xl font-bold tracking-tight text-white uppercase italic">
                        {DOCUMENTS.find(d => d.id === activeTab)?.title}
                      </h2>
                      <div className="text-[10px] font-mono text-blue-400 uppercase tracking-[0.2em]">
                        {DOCUMENTS.find(d => d.id === activeTab)?.version}
                      </div>
                    </div>
                    <div className="p-4 rounded-full bg-blue-500/10 border border-blue-500/20">
                      {DOCUMENTS.find(d => d.id === activeTab)?.icon}
                    </div>
                  </div>

                  {DOCUMENTS.find(d => d.id === activeTab)?.content}

                  <div className="pt-12 border-t border-white/5 flex flex-col sm:flex-row items-center justify-between gap-6 opacity-40 grayscale group hover:grayscale-0 hover:opacity-100 transition-all duration-700">
                    <div className="text-[10px] font-mono uppercase tracking-widest">
                      Guardian Command // Legal Intelligence Sector
                    </div>
                    <div className="flex items-center gap-4">
                      <Shield className="w-4 h-4" />
                      <Lock className="w-4 h-4" />
                      <Scale className="w-4 h-4" />
                    </div>
                  </div>
                </div>
              </motion.div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}

function StatusRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between text-[10px] font-mono">
      <span className="text-white/30 uppercase tracking-widest">{label}</span>
      <span className="text-blue-400 font-bold">{value}</span>
    </div>
  );
}
